<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-MassTransitDemo.Worker-5db816b9-5b1c-41a8-a0df-2e6caabb0a0b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="8.3.6" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../MassTransitDemo.Contracts/MassTransitDemo.Contracts.csproj" />
    <ProjectReference Include="../MassTransitDemo.ServiceDefaults/MassTransitDemo.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
